import {useMemo,useRef,useState} from 'react';
import {Plus,Minus,RotateCcw,Expand} from 'lucide-react';
import type {Field,PR} from './types';
interface Props {fields:Field[];prs:PR[];selected:string;onSelect:(id:string)=>void;expanded?:boolean;onExpand?:()=>void}
const POS:Record<string,[number,number]>={linear:[310,85],combinatorics:[95,112],circuits:[400,212],analysis:[252,266],numerical:[92,281],number:[190,182],formal:[370,333]};
export default function FieldMap({fields,prs,selected,onSelect,expanded,onExpand}:Props){
 const [hover,setHover]=useState('');const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const dragged=useRef(false);
 const counts=useMemo(()=>Object.fromEntries(fields.map(f=>[f.id,prs.filter(p=>p.fields.includes(f.id)).length])),[fields,prs]);
 const edges=useMemo(()=>fields.flatMap((a,i)=>fields.slice(i+1).map(b=>({a:a.id,b:b.id,n:prs.filter(p=>p.fields.includes(a.id)&&p.fields.includes(b.id)).length}))).filter(e=>e.n),[fields,prs]);
 const focus=hover||selected;const current=fields.find(f=>f.id===focus);const count=focus?counts[focus]:0;
 return <section className={'panel field-map '+(expanded?'expanded':'')}><div className="panel-head"><div><h2>Mathematical fields</h2><p>Connections show PR co-mentions</p></div>{onExpand&&<button className="icon-btn" aria-label="Expand field map" onClick={onExpand}><Expand size={16}/></button>}</div>
 <div className="map-wrap"><svg viewBox="0 0 480 385" role="group" aria-label="Interactive mathematical field map. Select a field to filter contributions." onPointerDown={e=>{if(e.target===e.currentTarget){drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};dragged.current=false;e.currentTarget.setPointerCapture(e.pointerId);}}} onPointerMove={e=>{if(drag.current){dragged.current=true;const rect=e.currentTarget.getBoundingClientRect();setPan({x:drag.current.px+(e.clientX-drag.current.x)*480/rect.width,y:drag.current.py+(e.clientY-drag.current.y)*385/rect.height});}}} onPointerUp={()=>{drag.current=null;}}>
 <defs><pattern id="dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="#45515a" opacity=".45"/></pattern></defs><rect width="480" height="385" fill="url(#dots)" pointerEvents="none"/>
 <g transform={`translate(${240+pan.x},${192+pan.y}) scale(${zoom}) translate(-240,-192)`}>
 {edges.map(e=>{const [x1,y1]=POS[e.a],[x2,y2]=POS[e.b];const highlight=!focus||focus===e.a||focus===e.b;return <g key={e.a+e.b}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={focus&&highlight?current?.color:'#60766b'} strokeWidth={1+Math.sqrt(e.n)*.35} strokeOpacity={highlight?.32:.06}/><title>{fields.find(f=>f.id===e.a)?.name} + {fields.find(f=>f.id===e.b)?.name}: {e.n} PR descriptions</title></g>;})}
 {fields.map(f=>{const [x,y]=POS[f.id];const r=14+Math.sqrt(counts[f.id]??0)*3.2;const connected=!focus||focus===f.id||edges.some(e=>(e.a===focus&&e.b===f.id)||(e.b===focus&&e.a===f.id));return <g key={f.id} className="field-node" tabIndex={0} role="button" aria-label={`${f.name}, ${counts[f.id]} pull requests${selected===f.id?', selected':''}`} aria-pressed={selected===f.id} onMouseEnter={()=>setHover(f.id)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(f.id)} onBlur={()=>setHover('')} onClick={()=>{if(!dragged.current)onSelect(selected===f.id?'':f.id);dragged.current=false;}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(selected===f.id?'':f.id);}}} opacity={connected?1:.25}><circle cx={x} cy={y} r={r+6} fill="none" stroke={f.color} strokeOpacity={focus===f.id?.55:.07}/><circle cx={x} cy={y} r={r} fill={f.color} fillOpacity=".08" stroke={f.color} strokeOpacity={focus===f.id?1:.5}/><text x={x} y={y+6} textAnchor="middle" fill={f.color} className="node-count">{counts[f.id]}</text><text x={x} y={y+r+23} textAnchor="middle" fill={f.color} className="node-label">{f.name}</text></g>;})}
 </g></svg><div className="map-controls"><button className="icon-btn" aria-label="Zoom into map" onClick={()=>setZoom(Math.min(zoom+.2,1.8))}><Plus size={15}/></button><button className="icon-btn" aria-label="Zoom out of map" onClick={()=>setZoom(Math.max(zoom-.2,.65))}><Minus size={15}/></button><button className="icon-btn" aria-label="Reset field map" onClick={()=>{setZoom(1);setPan({x:0,y:0});onSelect('');}}><RotateCcw size={14}/></button></div></div>
 <div className="map-caption">{current?<><i style={{background:current.color}}/>{current.name}<span>{count} contributions</span></>:<><i className="legend-dot"/>Select a field to filter PRs</>}</div>
 </section>;
}
