import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,ExternalLink,GitBranch,Minus,Plus,RotateCcw} from 'lucide-react';
import type {PR,Research} from './types';
import type {IdeaEdge} from '../lib/lineage.mjs';
import {ancestors,buildIdeaGraph} from '../lib/lineage.mjs';
import {date,time,shortSci} from './format';
import './lineage.css';
const ROOT='CrocSwap/integer-mult-bounds';
const ref=(p:PR)=>p.repo===ROOT?`#${p.number}`:`${p.repo.split('/')[0]} #${p.number}`;
interface Props {data:Research;matching:PR[];leaderId?:string;author:string;setAuthor:(v:string)=>void;query:string;status:string;includeDrafts:boolean;fieldFilter:string;scope:string;setScope:(v:string)=>void;onSelect:(p:PR)=>void}
export default function Lineage({data,matching,leaderId,author,setAuthor,query,status,includeDrafts,fieldFilter,scope,setScope,onSelect}:Props){
 const graph=useMemo(()=>buildIdeaGraph(scope==='all'?[...data.prs,...data.forks.flatMap(f=>f.prs)]:data.prs),[data,scope]);
 const showcase=graph.nodes.slice().reverse().find(p=>graph.edges.filter(e=>e.target===p.id&&e.kind==='reuse'&&e.chronological&&e.crossUser).length>=2)?.id||leaderId||graph.nodes.at(-1)?.id||'';
 const [focusId,setFocusId]=useState(showcase),[edgeId,setEdgeId]=useState(''),[view,setView]=useState('branch'),[deep,setDeep]=useState(false),[citations,setCitations]=useState(false),[sameAuthor,setSameAuthor]=useState(false),[zoom,setZoom]=useState(1),[hover,setHover]=useState(''),[pair,setPair]=useState(''),[limit,setLimit]=useState(10),[contextSelection,setContextSelection]=useState(false);
 const scrollRef=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(900);
 useEffect(()=>{if(!scrollRef.current)return;const observer=new ResizeObserver(entries=>setWidth(entries[0].contentRect.width));observer.observe(scrollRef.current);return()=>observer.disconnect();},[]);

 const byId=useMemo(()=>new Map(graph.nodes.map(p=>[p.id,p])),[graph]);
 const userNames=useMemo(()=>[...new Set(graph.nodes.map(p=>p.author))].sort(),[graph]);
 const matchingIds=useMemo(()=>new Set(matching.map(p=>p.id)),[matching]);
 const relevant=useMemo(()=>graph.edges.filter(e=>{
  const source=byId.get(e.source)!,target=byId.get(e.target)!;
  const permitted=(p:PR)=>(includeDrafts||!p.draft)&&(status==='all'||(status==='draft'?p.draft:p.state===status));
  return permitted(source)&&permitted(target)&& (sameAuthor||e.crossUser)&&(!author||source.author===author||target.author===author)&&(matchingIds.has(e.source)||matchingIds.has(e.target)||!!query&&e.evidence.toLowerCase().includes(query.toLowerCase())&&(!author||source.author===author||target.author===author));
 }),[graph,byId,matchingIds,sameAuthor,author,query,status,includeDrafts]);
 const eligible=useMemo(()=>relevant.filter(e=>citations||e.kind==='reuse'&&e.chronological),[relevant,citations]);
 const reuseLinks=relevant.filter(e=>e.kind==='reuse'&&e.chronological);
 const pairs=useMemo(()=>{
  const groups=new Map<string,{id:string;source:string;target:string;edges:IdeaEdge[]}>();
  for(const e of reuseLinks){const source=byId.get(e.source)!.author,target=byId.get(e.target)!.author,id=source+'→'+target;const group=groups.get(id)||{id,source,target,edges:[]};group.edges.push(e);groups.set(id,group);}
  return [...groups.values()].sort((a,b)=>b.edges.length-a.edges.length||a.source.localeCompare(b.source));
 },[relevant,byId]);
 useEffect(()=>{setPair('');setEdgeId('');setLimit(10);setContextSelection(false);},[author,query,scope,sameAuthor,citations,status,includeDrafts,fieldFilter]);
 const chosen=byId.get(focusId);
 const focus=chosen&&(contextSelection||eligible.some(e=>e.source===chosen.id||e.target===chosen.id)||matchingIds.has(chosen.id))?chosen:byId.get(eligible.at(-1)?.target||matching.at(-1)?.id||'');
 const relations=deep&&view==='branch'?graph.edges.filter(e=>e.kind==='reuse'&&e.chronological):eligible;
 const incoming=relations.filter(e=>e.target===focus?.id),outgoing=relations.filter(e=>e.source===focus?.id);
 const selectedPair=pairs.find(p=>p.id===pair);
 const displayed=useMemo(()=>{
  if(selectedPair){const ids=new Set(selectedPair.edges.flatMap(e=>[e.source,e.target]));return {nodes:graph.nodes.filter(p=>ids.has(p.id)),edges:selectedPair.edges};}
  if(view==='all'){const ids=new Set([...matchingIds,...eligible.flatMap(e=>[e.source,e.target])]);return {nodes:graph.nodes.filter(p=>ids.has(p.id)),edges:eligible};}
  if(!focus)return {nodes:[],edges:[]};
  const ancestryEdges=deep?graph.edges.filter(e=>e.kind==='reuse'&&e.chronological&&(sameAuthor||e.crossUser)):eligible;
  const ids=deep?ancestors(focus.id,ancestryEdges):new Set([focus.id]);
  for(const e of eligible)if(e.target===focus.id||e.source===focus.id){ids.add(e.source);ids.add(e.target);}
  return {nodes:graph.nodes.filter(p=>ids.has(p.id)),edges:ancestryEdges.filter(e=>ids.has(e.source)&&ids.has(e.target))};
 },[selectedPair,view,deep,focus,graph,eligible,matchingIds,sameAuthor]);
 const lanes=[...new Set(displayed.nodes.map(p=>p.author))];
 const gutter=width<500?112:128;
 const W=view==='branch'&&!deep&&!selectedPair?Math.max(260,width-gutter):Math.max(500,width-gutter,displayed.nodes.length*45+80),H=Math.max(230,lanes.length*68+80);
 const nodeWidth=Math.min(38,Math.max(26,(W-80)/Math.max(1,displayed.nodes.length-1)*.88)),half=nodeWidth/2;
 let axisCount=Math.min(width<500?2:5,displayed.nodes.length);
 while(axisCount>2&&Math.floor((displayed.nodes.length-1)/(axisCount-1))*(W-80)/Math.max(1,displayed.nodes.length-1)<110)axisCount--;
 const axisIndexes=new Set(Array.from({length:axisCount},(_,i)=>Math.round(i*(displayed.nodes.length-1)/Math.max(1,axisCount-1))));
 const positions=new Map(displayed.nodes.map((p,i)=>[p.id,{x:40+(displayed.nodes.length>1?i/(displayed.nodes.length-1):.5)*(W-80),y:50+lanes.indexOf(p.author)*68}]));
 const pathFor=(e:IdeaEdge)=>{const a=positions.get(e.source)!,b=positions.get(e.target)!,dx=b.x-a.x;const start=a.x+(dx>=0?half:-half),end=b.x+(dx>=0?-(half+2):half+2),bend=Math.max(28,Math.abs(dx)*.45);return `M${start},${a.y} C${start+(dx>=0?bend:-bend)},${a.y} ${end-(dx>=0?bend:-bend)},${b.y} ${end},${b.y}`;};
 const selectedEdge=graph.edges.find(e=>e.id===edgeId)||selectedPair?.edges[0]||incoming.find(e=>e.kind==='reuse'&&e.chronological)||incoming[0]||outgoing[0];
 const lit=new Set([focus?.id,...(selectedEdge?[selectedEdge.source,selectedEdge.target]:[])]);
 const hoverPR=byId.get(hover);
 const selectNode=(id:string)=>{setContextSelection(true);setFocusId(id);setEdgeId('');setPair('');};
 const selectEdge=(e:IdeaEdge)=>{setContextSelection(true);setEdgeId(e.id);setFocusId(e.target);setPair('');};
 const activeUsers=lanes.length;
 return <div className="lineage-view">
  <section className="panel lineage-panel"><div className="panel-head lineage-heading"><div><h2>Idea lineage <span className="subtle-pill">{reuseLinks.length} reuse links</span></h2><p>Reuse reported in PR descriptions</p></div><div className="panel-actions"><select aria-label="Lineage GitHub user" value={author} onChange={e=>setAuthor(e.target.value)}><option value="">All GitHub users</option>{userNames.map(a=><option key={a}>{a}</option>)}</select><select aria-label="Lineage repository scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="upstream">Upstream PRs</option><option value="all">Include fork PRs</option></select></div></div>
   <div className="lineage-controls"><div className="segmented small"><button className={view==='branch'?'active':''} onClick={()=>{setView('branch');setPair('');}}>Branch</button><button className={view==='all'?'active':''} onClick={()=>{setView('all');setPair('');}}>All PRs</button></div><select aria-label="Select lineage PR" value={focus?.id||''} onChange={e=>{selectNode(e.target.value);setView('branch');}}>{graph.nodes.slice().reverse().map(p=><option key={p.id} value={p.id}>{ref(p)} · {p.author}</option>)}</select>{view==='branch'&&<button className={'text-btn '+(deep?'accent-text':'')} aria-pressed={deep} onClick={()=>{setDeep(!deep);if(!deep)setSameAuthor(true);}}>All ancestors</button>}<div className="lineage-zoom"><button className="icon-btn" aria-label="Zoom out lineage" disabled={zoom<=.5} onClick={()=>setZoom(Math.max(.5,zoom-.25))}><Minus size={15}/></button><button className="icon-btn" aria-label="Zoom into lineage" disabled={zoom>=2} onClick={()=>setZoom(Math.min(2,zoom+.25))}><Plus size={15}/></button><button className="icon-btn" aria-label="Reset lineage graph" onClick={()=>{setZoom(1);setFocusId(showcase);setContextSelection(false);setPair('');setEdgeId('');setDeep(false);setSameAuthor(false);setCitations(false);setHover('');setView('branch');scrollRef.current?.scrollTo({left:0,top:0});}}><RotateCcw size={14}/></button></div></div>
   <div className="lineage-layout"><div className="lineage-diagram"><div className="lineage-scroll" ref={scrollRef} tabIndex={0} aria-label="Scrollable idea lineage timeline"><div className="lineage-canvas" style={{width:gutter+W*zoom,height:H*zoom}}><div className="lineage-lanes" style={{height:H*zoom,width:gutter}}><span className="lineage-lane-heading">GitHub user</span>{lanes.map((a,i)=><button key={a} style={{top:(50+i*68)*zoom-12}} title={`Filter ${a}`} className={a===author?'active':''} onClick={()=>setAuthor(author===a?'':a)}>{a}</button>)}</div><svg width={W*zoom} height={H*zoom} viewBox={`0 0 ${W} ${H}`} role="group" aria-label="Branching timeline of PR idea reuse. Arrows go from the source PR to the PR that reuses it.">
    <defs><marker id="reuse-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0,0 L8,4 L0,8 Z" fill="context-stroke"/></marker><pattern id="lineage-dots" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="#46535a" opacity=".35"/></pattern></defs><rect width={W} height={H} fill="url(#lineage-dots)"/>
    {lanes.map((a,i)=><g key={a}><rect x="0" y={24+i*68} width={W} height="54" fill={i%2?'#172025':'#131b20'} opacity=".45"/><line x1="0" x2={W} y1={50+i*68} y2={50+i*68} stroke="#35433e" strokeOpacity=".5" strokeDasharray="2 7"/></g>)}
    {displayed.edges.map(e=>{const active=selectedEdge?.id===e.id,used=e.kind==='reuse'&&e.chronological;return <g key={e.id} className="lineage-edge" tabIndex={0} role="button" aria-label={`${byId.get(e.source)!.author} ${ref(byId.get(e.source)!)} to ${byId.get(e.target)!.author} ${ref(byId.get(e.target)!)}: ${used?'reported reuse':e.chronological?e.kind:'later reference'}`} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();selectEdge(e);}}} onClick={()=>selectEdge(e)}><path d={pathFor(e)} fill="none" stroke={active?'#b9f582':used?'#73957b':'#737d87'} strokeWidth={active?2.5:1.4} strokeOpacity={active?1:used?.55:.35} strokeDasharray={used?undefined:'4 6'} markerEnd="url(#reuse-arrow)"/><path d={pathFor(e)} fill="none" stroke="transparent" strokeWidth="14"/>{active&&used&&<circle r="3" fill="#d5ffae" className="lineage-flow"><animateMotion dur="3s" repeatCount="indefinite" path={pathFor(e)}/></circle>}</g>;})}
    {displayed.nodes.map(p=>{const pos=positions.get(p.id)!,focused=focus?.id===p.id,highlight=lit.has(p.id),used=eligible.filter(e=>e.target===p.id&&e.kind==='reuse').length;return <g key={p.id} role="button" tabIndex={0} aria-label={`Explore ${ref(p)} by ${p.author}${p.draft?', draft':''}`} className={'lineage-node '+(focused?'is-focused':'')} onMouseEnter={()=>setHover(p.id)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(p.id)} onBlur={()=>setHover('')} onClick={()=>selectNode(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(p.id);}}}><title>{ref(p)} · {p.author} · {date(p.createdAt)} {time(p.createdAt)} UTC · {used} reuse links{p.bound?` · κ ${shortSci(p.bound.value)}`:''}</title>{focused&&<rect x={pos.x-25} y={pos.y-20} width="50" height="40" rx="16" fill="none" stroke="#b9f582" strokeOpacity=".3"/>}<rect x={pos.x-half} y={pos.y-13} width={nodeWidth} height="26" rx="9" fill={focused?'#b9f582':highlight?'#2b402d':'#202b2f'} stroke={focused?'#b9f582':highlight?'#77956a':'#536665'} strokeDasharray={p.draft?'3 3':undefined}/><text x={pos.x} y={pos.y+4} textAnchor="middle" fill={focused?'#132010':highlight?'#d1e9c5':'#b1c2bb'} fontSize="11" fontFamily="IBM Plex Mono, monospace">#{p.number}</text>{p.repo!==ROOT&&<text x={pos.x} y={pos.y+27} textAnchor="middle" className="axis-label">fork</text>}</g>;})}
    {displayed.nodes.filter((_,i)=>axisIndexes.has(i)).map(p=><text key={p.id} x={positions.get(p.id)!.x} y={H-15} textAnchor={p.id===displayed.nodes[0]?.id?'start':p.id===displayed.nodes.at(-1)?.id?'end':'middle'} className="axis-label">{date(p.createdAt)} {time(p.createdAt)}</text>)}
   </svg></div></div><div className="lineage-legend"><span><i className="legend-line"/>Reported reuse</span>{citations&&<span><i className="lineage-dashed"/>Other / later references</span>}<span className="meta">{displayed.nodes.length} PRs · {activeUsers} users</span></div>{hoverPR&&<div className="lineage-hover" style={{left:gutter+12}}><b>{ref(hoverPR)} · {hoverPR.author}</b><span>{hoverPR.title}</span><span>{date(hoverPR.createdAt)}, {time(hoverPR.createdAt)} UTC{hoverPR.draft?' · Draft':''}</span></div>}{!displayed.nodes.length&&<div className="empty-state">No matching PRs.</div>}</div>
   <aside className="lineage-inspector">{focus&&<><div className="lineage-focus"><span><GitBranch size={15}/>{ref(focus)} · {focus.author}{focus.draft&&<span className="draft-tag">Draft</span>}</span><button className="lineage-focus-title" onClick={()=>onSelect(focus)}>{focus.title}<ExternalLink size={13}/></button>{focus.bound&&<span className="meta">κ {shortSci(focus.bound.value)}</span>}</div><RelationList title="Used ideas from" edges={incoming.filter(e=>e.kind==='reuse'&&e.chronological)} byId={byId} selected={selectedEdge?.id} direction="source" onSelect={selectEdge}/><RelationList title="Used by" edges={outgoing.filter(e=>e.kind==='reuse'&&e.chronological)} byId={byId} selected={selectedEdge?.id} direction="target" onSelect={selectEdge}/></>}{selectedEdge&&<div className="lineage-evidence"><span className="lineage-evidence-kind">{selectedEdge.kind==='reuse'&&selectedEdge.chronological?'Reported reuse':selectedEdge.chronological?selectedEdge.kind==='comparison'?'Comparison':'Citation':'Later reference'} · {ref(byId.get(selectedEdge.target)!)}</span><div className="lineage-evidence-users">{byId.get(selectedEdge.source)!.author}<ArrowRight size={12}/>{byId.get(selectedEdge.target)!.author}</div><blockquote>{selectedEdge.evidence}</blockquote><a href={byId.get(selectedEdge.target)!.url} target="_blank" rel="noreferrer">Read source PR<ExternalLink size={12}/></a></div>}{!selectedEdge&&<p className="lineage-no-evidence">No explicit PR reuse link matches this selection.</p>}</aside></div>
   <div className="lineage-footer"><label className="checkbox"><input type="checkbox" checked={citations} onChange={e=>setCitations(e.target.checked)}/>Other citations</label><label className="checkbox"><input type="checkbox" checked={sameAuthor} onChange={e=>setSameAuthor(e.target.checked)}/>Same author</label><span>PR opening order · current descriptions</span></div>
  </section>
  <section className="panel lineage-pairs"><div className="panel-head"><div><h2>User connections <span className="subtle-pill">{pairs.length}</span></h2><p>Source of ideas → author who reused them</p></div>{pair&&<button className="text-btn" onClick={()=>setPair('')}>Clear pair</button>}</div><div className="lineage-pair-grid">{pairs.slice(0,limit).map(p=><button key={p.id} className={'lineage-pair '+(pair===p.id?'selected':'')} onClick={()=>{setPair(pair===p.id?'':p.id);setFocusId(p.edges.at(-1)!.target);setEdgeId(p.edges.at(-1)!.id);scrollRef.current?.scrollTo({left:0,top:0});}}><span>{p.source}</span><ArrowRight size={15}/><span>{p.target}</span><b>{p.edges.length}<small>PR {p.edges.length===1?'link':'links'}</small></b></button>)}</div>{pairs.length>limit&&<button className="load-more" onClick={()=>setLimit(n=>n+12)}>Show more connections</button>}{!pairs.length&&<div className="empty-state">No reported reuse between users matches these filters.</div>}</section>
  <details className="lineage-method"><summary>How links are identified</summary><p>Solid arrows require explicit reuse, composition, inheritance, or dependency language near a PR reference. Comparisons and general credit lists are separate. Claims come from current descriptions and are not proof of priority or mathematical dependence. Similar methods alone create no link.</p><p>Ancestor expansion keeps earlier PRs as context, including the same author’s intermediate work. The timeline preserves PR opening order; spacing is uniform for readability. Later references added to earlier PR descriptions appear only with “Other citations” and do not enter the ancestry graph. Unresolved PR references cannot be drawn. {graph.missing.length>0&&`${graph.missing.length} references point outside the available PR set.`} Attribution without an identifiable PR remains in its source description. Every displayed connection exposes its source excerpt. Fork-local bare references are resolved within that fork.</p></details>
 </div>;
}
function RelationList({title,edges,byId,selected,direction,onSelect}:{title:string;edges:IdeaEdge[];byId:Map<string,PR>;selected?:string;direction:'source'|'target';onSelect:(e:IdeaEdge)=>void}){
 if(!edges.length)return null;
 return <div className="lineage-relations"><h3>{title}<span>{edges.length}</span></h3><div>{edges.map(e=>{const p=byId.get(e[direction])!;return <button key={e.id} className={selected===e.id?'selected':''} onClick={()=>onSelect(e)}><span>{p.author}</span><code>{ref(p)}</code><ArrowRight size={13}/></button>;})}</div></div>;
}
