export interface Bound {value:number;expression:string;kind:'exact'|'lower';evidence:string;source:string}
export interface Method {id:string;name:string;fields:string[];evidence:string}
export interface Field {id:string;name:string;color:string;description:string}
export interface Checkpoint {id:string;kind:'openai'|'checkpoint'|'reviewed';repo:string;commit:string;title:string;author:string;createdAt:string;manuscriptDate?:string|null;url:string;commitUrl:string;bound:Bound;methods:Method[];fields:string[];review?:{sourcePR:number;head:string;scope:string;reviewUrl:string;validationUrl:string;proofUrl:string|null;certificateUrl:string|null;reproduce:string|null;previousBound:Bound|null}}
export interface ReviewedCheckpoint extends Checkpoint {kind:'reviewed';review:NonNullable<Checkpoint['review']>}
export interface MaintainerRecord {current:ReviewedCheckpoint|null;history:ReviewedCheckpoint[]}
export interface PR {id:string;repo:string;number:number;title:string;body:string;url:string;author:string;avatar:string;createdAt:string;updatedAt:string;closedAt:string|null;mergedAt:string|null;state:string;draft:boolean;headRepo:string|null;headBranch:string;headSha:string;baseSha:string;labels:string[];bound:Bound|null;methods:Method[];fields:string[];references:number[]}
export interface Fork {name:string;owner:string;avatar:string;url:string;createdAt:string;pushedAt:string;defaultBranch:string;description:string|null;stars:number;forkCount:number;prs:PR[];readme:string|null;readmeUrl:string|null;readmeMatchesMain?:boolean;fields:string[];methods:Method[];bound:Bound|null}
export interface Research {schemaVersion:number;fetchedAt:string;live?:boolean;refreshError?:string;history:Checkpoint[];maintainer?:MaintainerRecord;repository:{createdAt?:string;name:string;url:string;description:string;defaultBranch:string;stars:number;forkCount:number;pushedAt:string;readmeUrl:string;readme:string;bound:Bound|null;fields:string[];methods:Method[]};fields:Field[];prs:PR[];forks:Fork[];warnings:string[];coverage:{publicForks:number;reportedForks:number;rootPRs:number;forkPRs:number;apiRemaining:string|null};methodology:string}
